/*
 * APS API (Formly Forge API)
 *
 * APS API based on https://aps.autodesk.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ApsNET.Api;
using ApsNET.Model;
using ApsNET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ApsNET.Test.Model
{
    /// <summary>
    ///  Class for testing Bearer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BearerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Bearer
        //private Bearer instance;

        public BearerTests()
        {
            // TODO uncomment below to create an instance of Bearer
            //instance = new Bearer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Bearer
        /// </summary>
        [Fact]
        public void BearerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Bearer
            //Assert.IsType<Bearer>(instance);
        }


        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

    }

}
