/*
 * APS API (Formly Forge API)
 *
 * APS API based on https://aps.autodesk.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ApsNET.Client;
using ApsNET.Api;
// uncomment below to import models
//using ApsNET.Model;

namespace ApsNET.Test.Api
{
    /// <summary>
    ///  Class for testing TwoLeggedApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TwoLeggedApiTests : IDisposable
    {
        private TwoLeggedApi instance;

        public TwoLeggedApiTests()
        {
            instance = new TwoLeggedApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwoLeggedApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TwoLeggedApi
            Assert.IsType<TwoLeggedApi>(instance);
        }

        /// <summary>
        /// Test AuthenticationV1AuthenticatePost
        /// </summary>
        [Fact]
        public void AuthenticationV1AuthenticatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //string clientSecret = null;
            //string grantType = null;
            //string scopes = null;
            //var response = instance.AuthenticationV1AuthenticatePost(clientId, clientSecret, grantType, scopes);
            //Assert.IsType<Bearer>(response);
        }
    }
}
